"===============================================================
" Summary: vimrc
"  Author: gomoh
"===============================================================

"---------------------------------------------------------------
" Init: "{{{
"---------------------------------------------------------------
set nocompatible
set all&
filetype detect
"}}}

"---------------------------------------------------------------
" Common: "{{{
"---------------------------------------------------------------
set modeline
set cryptmethod=blowfish
set helplang=ja,en
set spell
set spelllang+=cjk
"}}}

"---------------------------------------------------------------
" Encoding: "{{{
"---------------------------------------------------------------
set encoding=utf-8
scriptencoding utf-8

set fileencoding=utf-8
set fileencodings=utf-8,cp932

set fileformat=unix
"}}}

"---------------------------------------------------------------
" Plugin Option: "{{{
"---------------------------------------------------------------
" Neocomplete:
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 1

" Unite:
let g:unite_enable_start_insert = 1

"}}}

"---------------------------------------------------------------
" Dein: "{{{
"---------------------------------------------------------------
" dein.vim directory.
let s:work = expand('~/.vim/dein.d')
let s:dein = s:work . '/repos/github.com/Shougo/dein.vim'
let s:toml = expand('~/.vim/plugins.toml')

if &compatible
  set nocompatible
endif

" dein.vim install.
if !isdirectory(s:dein)
  execute '!git clone https://github.com/Shougo/dein.vim' s:dein
endif

execute 'set runtimepath^=' . s:dein

call dein#begin(s:work)
call dein#load_toml(s:toml)
call dein#end()

filetype plugin indent on

if dein#check_install()
  call dein#install()
endif
"}}}

"---------------------------------------------------------------
" Backup Swap Info: "{{{
"---------------------------------------------------------------
set nobackup
set swapfile
set noundofile
set viminfo=
"}}}

"---------------------------------------------------------------
" Edit: "{{{
"---------------------------------------------------------------
set backspace=indent,eol,start
"}}}

"---------------------------------------------------------------
" Visual: "{{{
"---------------------------------------------------------------
set number

" realtime = matchtime * 100ms
set showmatch
set matchtime=8

set list
set listchars=tab:^_,trail:^
"}}}

"---------------------------------------------------------------
" Indent: "{{{
"---------------------------------------------------------------
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set shiftround

set autoindent
set smartindent
"}}}

"---------------------------------------------------------------
" Search: "{{{
"---------------------------------------------------------------
set ignorecase
set smartcase
set incsearch
set hlsearch
"}}}

"---------------------------------------------------------------
" Status Line: "{{{
"---------------------------------------------------------------
set laststatus=2
set statusline=%<%F%m\ %r%h%w[%{(&fenc!=''?&fenc:&enc)}][%{&fileformat}]%y%=[ASCII=%03.3b,0x%02.2B][%4cC,\ %l/%LL][%P]
"}}}

"---------------------------------------------------------------
" Command Line: "{{{
"---------------------------------------------------------------
set showcmd
set noshowmode

set wildmenu
set wildmode=list:longest
"}}}

"---------------------------------------------------------------
" ColorScheme: "{{{
"---------------------------------------------------------------
set t_Co=256
colorscheme wombat256
syntax on
"}}}

"---------------------------------------------------------------
" Key Map: "{{{
"---------------------------------------------------------------
" US keyboard
nnoremap : ;
nnoremap ; :
vnoremap : ;
vnoremap ; :

" Neocomplete:
inoremap <C-n> <C-x><C-u>
inoremap <C-p> <C-x><C-u>

" Unite:
nmap <C-U> [Unite]
nnoremap <silent> [Unite]<C-B> :Unite buffer<CR>
nnoremap <silent> [Unite]<C-F> :Unite file_rec/async<CR>
nnoremap <silent> [Unite]<C-R> :Unite file_rec/async:<C-r>=expand("%:p:h:")<CR><CR>
nnoremap <silent> [Unite]<C-T> :Unite tab<CR>
"}}}

"---------------------------------------------------------------
" Autocmd: "{{{
"---------------------------------------------------------------
augroup MyVimrc
  autocmd!
  autocmd BufWritePost $MYVIMRC nested source $MYVIMRC | redraw | echo "reload " . $MYVIMRC
augroup END
"}}}

set secure
