#!/bin/bash
# TODO check depend packages.
# ( build-essential git libncurses5-dev liblua5.1-0-dev )
# [ dpkg -s {package} ] return code.
# TODO check luajit.

cpu_cores=`cat /proc/cpuinfo | grep processor | wc -l`
hash_cmd="git log -1 --pretty=format:\"%h\" | cat"

repository=git://github.com/vim-jp/vim.git
srcdir=~/usr/src/vim
# NOTE. configure script do not expand "~".
configure_options=(
--prefix=${HOME}/usr
--enable-multibyte
--enable-fontset
--with-features=huge
--enable-luainterp=yes
--with-luajit
)

# init repository.
if [[ ! -d ${srcdir} ]]; then
  git clone ${repository} ${srcdir}
  F_force=defined
fi

# working in git repository.
cd ${srcdir}

# repository cleanup.
git reset --hard HEAD --quiet
git clean -df --quiet

# get commit hash.
old_hash=`eval ${hash_cmd}`
git pull
new_hash=`eval ${hash_cmd}`

# if there is update.
if [[ ${old_hash} != ${new_hash} || -n ${F_force} ]]; then
  ./configure ${configure_options[@]} && make -j ${cpu_cores} && make install
fi

